name: Scrape Subreddit

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install praw
        pip install markdown2  # Install markdown2 for markdown to HTML conversion

    - name: Run the script
      run: python main.py  # Replace with your script's filename

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "chathindun@gmail.com"  # Replace with your GitHub email
        git config --global user.name "ChathinduN"               # Replace with your GitHub username
        git add .
        git commit -m "Add scraped files" || echo "No changes to commit"  # Prevent failure if no changes
        git push
